# Generated by Django 3.1.7 on 2021-04-05 05:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoingreso', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='Monto Ingresos')),
                ('montoegreso', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='Monto Egresos')),
                ('fechamovimiento', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Movimiento')),
                ('motivoaccion', models.CharField(max_length=150, verbose_name='Motivo')),
                ('operacion', models.CharField(max_length=10, verbose_name='Operación')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'db_table': 'caja',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('nro_documento', models.CharField(max_length=10, unique=True, verbose_name='C.I')),
                ('nro_telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nro. Telefono')),
                ('direccion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Direccion')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecompleto', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('nro_documento', models.CharField(blank=True, max_length=10, null=True, verbose_name='C.I')),
                ('nro_telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nro. Telefono')),
                ('fechacompra', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Compra')),
                ('producto', models.CharField(max_length=150, verbose_name='Producto')),
                ('montocompra', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Monto Compra')),
                ('observaciones', models.CharField(blank=True, max_length=150, null=True, verbose_name='Observaciones')),
                ('estado', models.CharField(blank=True, max_length=15, null=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vendidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaventa', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Venta')),
                ('nombrecomprador', models.CharField(max_length=100, verbose_name='Nombre del Comprador')),
                ('montoventa', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Monto Vendido')),
                ('producto', models.CharField(max_length=150, verbose_name='Producto')),
                ('observaciones', models.CharField(blank=True, max_length=150, null=True, verbose_name='Observaciones')),
                ('tipoarticulo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo de Artículo')),
                ('codarticulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.compras', verbose_name='Cod. Artículo')),
            ],
            options={
                'verbose_name': 'Vendido',
                'verbose_name_plural': 'Vendidos',
                'db_table': 'vendidos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idprestamo', models.PositiveIntegerField(default=0, verbose_name='Cod. Prestamo')),
                ('fechaprestamo', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Prestamo')),
                ('producto', models.CharField(max_length=150, verbose_name='Producto')),
                ('interes', models.PositiveIntegerField(default=0, verbose_name='Interes')),
                ('montototal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Monto Total')),
                ('observaciones', models.CharField(blank=True, max_length=150, null=True, verbose_name='Observaciones')),
                ('fechavencimiento', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha Vencimiento')),
                ('estado', models.CharField(blank=True, max_length=15, null=True, verbose_name='Estado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.clientes', verbose_name='Cod. Cliente')),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
                'db_table': 'prestamos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrerecibo', models.CharField(max_length=50, verbose_name='Nombre')),
                ('fechapago', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Pago')),
                ('montopago', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Monto Pagado')),
                ('codprestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.prestamos', verbose_name='Cod. Prestamo')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Entregados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaprestamo', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Prestamo')),
                ('fechaentrega', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Entrega')),
                ('montoprestamo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Monto Prestado')),
                ('interes', models.PositiveIntegerField(default=0, verbose_name='Interes')),
                ('montoapagar', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Monto a Pagar')),
                ('montopagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Monto Pagado')),
                ('codprestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.prestamos', verbose_name='Cod. Prestamo')),
            ],
            options={
                'verbose_name': 'Entregado',
                'verbose_name_plural': 'Entregados',
                'db_table': 'entregados',
                'ordering': ['id'],
            },
        ),
    ]
