# Generated by Django 3.1.7 on 2021-04-05 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0002_auto_20210405_0204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='data_creaction',
            new_name='date_creation',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erp_clientes_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erp_clientes_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
